				<?php if ($breadcrumb): ?>
		      <div id="breadcrumb">
		      	<?php print $breadcrumb; ?>
		      </div> <!-- //#breadcrumb -->
		    <?php endif; ?>
				
				<?php if ($messages): ?>
			    <?php print $messages; ?>
			  <?php endif; ?>
			  
		    <?php if ($help): ?>
			    <?php print $help; ?>
			  <?php endif; ?>
		    
		    <?php if ($tabs): ?>
		    	<?php print $tabs ?>
		    <?php endif; ?>